apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab25-jenkins-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: lab25-jenkins
  template:
    metadata:
      labels:
        app: lab25-jenkins
    spec:
      containers:
      - name: app
        image: ashishmondal420/lab23-jenkins-cicd:latest
        ports:
        - containerPort: 3000
